//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:amap_location_fluttify/src/ios/ios.export.g.dart';
import 'package:amap_location_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import
class com_amap_location_common_network_HttpResponse extends java_lang_Object  {
  // generate getters
  Future<int> get_statusCode() async {
    final result = await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod("com.amap.location.common.network.HttpResponse::get_statusCode", {'refId': refId});
  
    return result;
  }
  
  Future<Uint8List> get_body() async {
    final result = await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod("com.amap.location.common.network.HttpResponse::get_body", {'refId': refId});
  
    return result;
  }
  

  // generate setters
  Future<void> set_statusCode(int statusCode) async {
    await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod('com.amap.location.common.network.HttpResponse::set_statusCode', {'refId': refId, "statusCode": statusCode});
  
  
  }
  
  Future<void> set_body(Uint8List body) async {
    await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod('com.amap.location.common.network.HttpResponse::set_body', {'refId': refId, "body": body});
  
  
  }
  

  // generate methods
  
}