//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:amap_location_fluttify/src/ios/ios.export.g.dart';
import 'package:amap_location_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import
class com_amap_location_common_network_HttpRequest extends java_lang_Object  {
  // generate getters
  Future<String> get_url() async {
    final result = await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod("com.amap.location.common.network.HttpRequest::get_url", {'refId': refId});
  
    return result;
  }
  
  Future<Uint8List> get_body() async {
    final result = await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod("com.amap.location.common.network.HttpRequest::get_body", {'refId': refId});
  
    return result;
  }
  
  Future<int> get_timeout() async {
    final result = await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod("com.amap.location.common.network.HttpRequest::get_timeout", {'refId': refId});
  
    return result;
  }
  

  // generate setters
  Future<void> set_url(String url) async {
    await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod('com.amap.location.common.network.HttpRequest::set_url', {'refId': refId, "url": url});
  
  
  }
  
  Future<void> set_body(Uint8List body) async {
    await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod('com.amap.location.common.network.HttpRequest::set_body', {'refId': refId, "body": body});
  
  
  }
  
  Future<void> set_timeout(int timeout) async {
    await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod('com.amap.location.common.network.HttpRequest::set_timeout', {'refId': refId, "timeout": timeout});
  
  
  }
  

  // generate methods
  
}