//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:amap_location_fluttify/src/ios/ios.export.g.dart';
import 'package:amap_location_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import
mixin com_amap_location_offline_IOfflineCloudConfig on java_lang_Object {
  

  

  @mustCallSuper
  Future<bool> isEnable() {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('isEnable::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<int> getConfigTime() {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('getConfigTime::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<bool> clearAll() {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('clearAll::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<int> getTrainingThreshold() {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('getTrainingThreshold::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<int> getMinWifiNum() {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('getMinWifiNum::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<List<String>> getContentProviderList() {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('getContentProviderList::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<int> getMaxRequestTimes() {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('getMaxRequestTimes::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<int> getMaxNonWifiRequestTimes() {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('getMaxNonWifiRequestTimes::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<int> getMaxNumPerRequest() {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('getMaxNumPerRequest::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
  @mustCallSuper
  Future<bool> getNeedFirstDownload() {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('getNeedFirstDownload::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
}