//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:amap_location_fluttify/src/ios/ios.export.g.dart';
import 'package:amap_location_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import
class com_amap_location_common_log_LogConfig_Builder extends java_lang_Object  {
  // generate getters
  

  // generate setters
  

  // generate methods
  Future<com_amap_location_common_log_LogConfig_Builder> setLogcatEnable(bool var1) async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.amap.location.common.log.LogConfig.Builder@$refId::setLogcatEnable([\'var1\':$var1])');
    }
  
    // invoke native method
    final result = await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod('com.amap.location.common.log.LogConfig.Builder::setLogcatEnable', {"var1": var1, "refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
      kNativeObjectPool.add(com_amap_location_common_log_LogConfig_Builder()..refId = result..tag = 'amap_location_fluttify');
      return com_amap_location_common_log_LogConfig_Builder()..refId = result..tag = 'amap_location_fluttify';
    }
  }
  
  Future<com_amap_location_common_log_LogConfig_Builder> setFileLogEnable(bool var1) async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.amap.location.common.log.LogConfig.Builder@$refId::setFileLogEnable([\'var1\':$var1])');
    }
  
    // invoke native method
    final result = await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod('com.amap.location.common.log.LogConfig.Builder::setFileLogEnable', {"var1": var1, "refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
      kNativeObjectPool.add(com_amap_location_common_log_LogConfig_Builder()..refId = result..tag = 'amap_location_fluttify');
      return com_amap_location_common_log_LogConfig_Builder()..refId = result..tag = 'amap_location_fluttify';
    }
  }
  
  Future<com_amap_location_common_log_LogConfig_Builder> setServerLogEnable(bool var1) async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.amap.location.common.log.LogConfig.Builder@$refId::setServerLogEnable([\'var1\':$var1])');
    }
  
    // invoke native method
    final result = await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod('com.amap.location.common.log.LogConfig.Builder::setServerLogEnable', {"var1": var1, "refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
      kNativeObjectPool.add(com_amap_location_common_log_LogConfig_Builder()..refId = result..tag = 'amap_location_fluttify');
      return com_amap_location_common_log_LogConfig_Builder()..refId = result..tag = 'amap_location_fluttify';
    }
  }
  
  Future<com_amap_location_common_log_LogConfig_Builder> setTraceWriteToFile(bool var1) async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.amap.location.common.log.LogConfig.Builder@$refId::setTraceWriteToFile([\'var1\':$var1])');
    }
  
    // invoke native method
    final result = await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod('com.amap.location.common.log.LogConfig.Builder::setTraceWriteToFile', {"var1": var1, "refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
      kNativeObjectPool.add(com_amap_location_common_log_LogConfig_Builder()..refId = result..tag = 'amap_location_fluttify');
      return com_amap_location_common_log_LogConfig_Builder()..refId = result..tag = 'amap_location_fluttify';
    }
  }
  
  Future<com_amap_location_common_log_LogConfig_Builder> setTraceUpToServer(bool var1) async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.amap.location.common.log.LogConfig.Builder@$refId::setTraceUpToServer([\'var1\':$var1])');
    }
  
    // invoke native method
    final result = await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod('com.amap.location.common.log.LogConfig.Builder::setTraceUpToServer', {"var1": var1, "refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
      kNativeObjectPool.add(com_amap_location_common_log_LogConfig_Builder()..refId = result..tag = 'amap_location_fluttify');
      return com_amap_location_common_log_LogConfig_Builder()..refId = result..tag = 'amap_location_fluttify';
    }
  }
  
  Future<com_amap_location_common_log_LogConfig_Builder> setLogMemoryBufferSize(int var1) async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.amap.location.common.log.LogConfig.Builder@$refId::setLogMemoryBufferSize([\'var1\':$var1])');
    }
  
    // invoke native method
    final result = await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod('com.amap.location.common.log.LogConfig.Builder::setLogMemoryBufferSize', {"var1": var1, "refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
      kNativeObjectPool.add(com_amap_location_common_log_LogConfig_Builder()..refId = result..tag = 'amap_location_fluttify');
      return com_amap_location_common_log_LogConfig_Builder()..refId = result..tag = 'amap_location_fluttify';
    }
  }
  
  Future<com_amap_location_common_log_LogConfig_Builder> setSignalLogFileLimit(int var1) async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.amap.location.common.log.LogConfig.Builder@$refId::setSignalLogFileLimit([\'var1\':$var1])');
    }
  
    // invoke native method
    final result = await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod('com.amap.location.common.log.LogConfig.Builder::setSignalLogFileLimit', {"var1": var1, "refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
      kNativeObjectPool.add(com_amap_location_common_log_LogConfig_Builder()..refId = result..tag = 'amap_location_fluttify');
      return com_amap_location_common_log_LogConfig_Builder()..refId = result..tag = 'amap_location_fluttify';
    }
  }
  
  Future<com_amap_location_common_log_LogConfig_Builder> setLogFileMaxCount(int var1) async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.amap.location.common.log.LogConfig.Builder@$refId::setLogFileMaxCount([\'var1\':$var1])');
    }
  
    // invoke native method
    final result = await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod('com.amap.location.common.log.LogConfig.Builder::setLogFileMaxCount', {"var1": var1, "refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
      kNativeObjectPool.add(com_amap_location_common_log_LogConfig_Builder()..refId = result..tag = 'amap_location_fluttify');
      return com_amap_location_common_log_LogConfig_Builder()..refId = result..tag = 'amap_location_fluttify';
    }
  }
  
  Future<com_amap_location_common_log_LogConfig> build(com_amap_location_common_log_LogConfig_Product var1, String var2) async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.amap.location.common.log.LogConfig.Builder@$refId::build([\'var2\':$var2])');
    }
  
    // invoke native method
    final result = await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod('com.amap.location.common.log.LogConfig.Builder::build', {"var1": var1.index, "var2": var2, "refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
      kNativeObjectPool.add(com_amap_location_common_log_LogConfig()..refId = result..tag = 'amap_location_fluttify');
      return com_amap_location_common_log_LogConfig()..refId = result..tag = 'amap_location_fluttify';
    }
  }
  
}