//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import
enum com_amap_location_common_log_LogConfig_Product {
  FLP,
  NLP,
  SDK
}