//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:amap_location_fluttify/src/ios/ios.export.g.dart';
import 'package:amap_location_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import
class com_amap_location_collection_CollectionConfig_TrackCollectorConfig extends java_lang_Object  {
  // generate getters
  Future<int> get_mLocScene() async {
    final result = await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod("com.amap.location.collection.CollectionConfig.TrackCollectorConfig::get_mLocScene", {'refId': refId});
  
    return result;
  }
  

  // generate setters
  Future<void> set_mLocScene(int mLocScene) async {
    await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod('com.amap.location.collection.CollectionConfig.TrackCollectorConfig::set_mLocScene', {'refId': refId, "mLocScene": mLocScene});
  
  
  }
  

  // generate methods
  Future<int> getLocScene() async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.amap.location.collection.CollectionConfig.TrackCollectorConfig@$refId::getLocScene([])');
    }
  
    // invoke native method
    final result = await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod('com.amap.location.collection.CollectionConfig.TrackCollectorConfig::getLocScene', {"refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
    
      return result;
    }
  }
  
  Future<void> setLocScene(String var1) async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.amap.location.collection.CollectionConfig.TrackCollectorConfig@$refId::setLocScene([\'var1\':$var1])');
    }
  
    // invoke native method
    final result = await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod('com.amap.location.collection.CollectionConfig.TrackCollectorConfig::setLocScene', {"var1": var1, "refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
    
      return result;
    }
  }
  
  Future<bool> isEnabled() async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.amap.location.collection.CollectionConfig.TrackCollectorConfig@$refId::isEnabled([])');
    }
  
    // invoke native method
    final result = await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod('com.amap.location.collection.CollectionConfig.TrackCollectorConfig::isEnabled', {"refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
    
      return result;
    }
  }
  
  Future<void> setEnabled(bool var1) async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.amap.location.collection.CollectionConfig.TrackCollectorConfig@$refId::setEnabled([\'var1\':$var1])');
    }
  
    // invoke native method
    final result = await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod('com.amap.location.collection.CollectionConfig.TrackCollectorConfig::setEnabled', {"var1": var1, "refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
    
      return result;
    }
  }
  
  Future<bool> isCollectSatellites() async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.amap.location.collection.CollectionConfig.TrackCollectorConfig@$refId::isCollectSatellites([])');
    }
  
    // invoke native method
    final result = await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod('com.amap.location.collection.CollectionConfig.TrackCollectorConfig::isCollectSatellites', {"refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
    
      return result;
    }
  }
  
  Future<void> setCollectSatellites(bool var1) async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.amap.location.collection.CollectionConfig.TrackCollectorConfig@$refId::setCollectSatellites([\'var1\':$var1])');
    }
  
    // invoke native method
    final result = await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod('com.amap.location.collection.CollectionConfig.TrackCollectorConfig::setCollectSatellites', {"var1": var1, "refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
    
      return result;
    }
  }
  
}