//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:amap_location_fluttify/src/ios/ios.export.g.dart';
import 'package:amap_location_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import
class com_amap_location_collection_CollectionConfig extends java_lang_Object  {
  // generate getters
  

  // generate setters
  

  // generate methods
  Future<int> getProductId() async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.amap.location.collection.CollectionConfig@$refId::getProductId([])');
    }
  
    // invoke native method
    final result = await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod('com.amap.location.collection.CollectionConfig::getProductId', {"refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
    
      return result;
    }
  }
  
  Future<void> setProductId(int var1) async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.amap.location.collection.CollectionConfig@$refId::setProductId([\'var1\':$var1])');
    }
  
    // invoke native method
    final result = await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod('com.amap.location.collection.CollectionConfig::setProductId', {"var1": var1, "refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
    
      return result;
    }
  }
  
  Future<String> getProductVersion() async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.amap.location.collection.CollectionConfig@$refId::getProductVersion([])');
    }
  
    // invoke native method
    final result = await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod('com.amap.location.collection.CollectionConfig::getProductVersion', {"refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
    
      return result;
    }
  }
  
  Future<void> setProductVersion(String var1) async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.amap.location.collection.CollectionConfig@$refId::setProductVersion([\'var1\':$var1])');
    }
  
    // invoke native method
    final result = await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod('com.amap.location.collection.CollectionConfig::setProductVersion', {"var1": var1, "refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
    
      return result;
    }
  }
  
  Future<String> getLicense() async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.amap.location.collection.CollectionConfig@$refId::getLicense([])');
    }
  
    // invoke native method
    final result = await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod('com.amap.location.collection.CollectionConfig::getLicense', {"refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
    
      return result;
    }
  }
  
  Future<void> setLicense(String var1) async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.amap.location.collection.CollectionConfig@$refId::setLicense([\'var1\':$var1])');
    }
  
    // invoke native method
    final result = await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod('com.amap.location.collection.CollectionConfig::setLicense', {"var1": var1, "refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
    
      return result;
    }
  }
  
  Future<String> getMapkey() async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.amap.location.collection.CollectionConfig@$refId::getMapkey([])');
    }
  
    // invoke native method
    final result = await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod('com.amap.location.collection.CollectionConfig::getMapkey', {"refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
    
      return result;
    }
  }
  
  Future<void> setMapkey(String var1) async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.amap.location.collection.CollectionConfig@$refId::setMapkey([\'var1\':$var1])');
    }
  
    // invoke native method
    final result = await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod('com.amap.location.collection.CollectionConfig::setMapkey', {"var1": var1, "refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
    
      return result;
    }
  }
  
  Future<String> getUtdid() async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.amap.location.collection.CollectionConfig@$refId::getUtdid([])');
    }
  
    // invoke native method
    final result = await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod('com.amap.location.collection.CollectionConfig::getUtdid', {"refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
    
      return result;
    }
  }
  
  Future<void> setUtdid(String var1) async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.amap.location.collection.CollectionConfig@$refId::setUtdid([\'var1\':$var1])');
    }
  
    // invoke native method
    final result = await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod('com.amap.location.collection.CollectionConfig::setUtdid', {"var1": var1, "refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
    
      return result;
    }
  }
  
  Future<bool> isStopCollectionWhenScreenOff() async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.amap.location.collection.CollectionConfig@$refId::isStopCollectionWhenScreenOff([])');
    }
  
    // invoke native method
    final result = await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod('com.amap.location.collection.CollectionConfig::isStopCollectionWhenScreenOff', {"refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
    
      return result;
    }
  }
  
  Future<void> setStopCollectionWhenScreenOff(bool var1) async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.amap.location.collection.CollectionConfig@$refId::setStopCollectionWhenScreenOff([\'var1\':$var1])');
    }
  
    // invoke native method
    final result = await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod('com.amap.location.collection.CollectionConfig::setStopCollectionWhenScreenOff', {"var1": var1, "refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
    
      return result;
    }
  }
  
  Future<com_amap_location_collection_CollectionConfig_FpsCollectorConfig> getFpsCollectorConfig() async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.amap.location.collection.CollectionConfig@$refId::getFpsCollectorConfig([])');
    }
  
    // invoke native method
    final result = await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod('com.amap.location.collection.CollectionConfig::getFpsCollectorConfig', {"refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
      kNativeObjectPool.add(com_amap_location_collection_CollectionConfig_FpsCollectorConfig()..refId = result..tag = 'amap_location_fluttify');
      return com_amap_location_collection_CollectionConfig_FpsCollectorConfig()..refId = result..tag = 'amap_location_fluttify';
    }
  }
  
  Future<com_amap_location_collection_CollectionConfig_TrackCollectorConfig> getTrackCollectorConfig() async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.amap.location.collection.CollectionConfig@$refId::getTrackCollectorConfig([])');
    }
  
    // invoke native method
    final result = await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod('com.amap.location.collection.CollectionConfig::getTrackCollectorConfig', {"refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
      kNativeObjectPool.add(com_amap_location_collection_CollectionConfig_TrackCollectorConfig()..refId = result..tag = 'amap_location_fluttify');
      return com_amap_location_collection_CollectionConfig_TrackCollectorConfig()..refId = result..tag = 'amap_location_fluttify';
    }
  }
  
  Future<com_amap_location_collection_CollectionConfig_UploadConfig> getUploadConfig() async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.amap.location.collection.CollectionConfig@$refId::getUploadConfig([])');
    }
  
    // invoke native method
    final result = await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod('com.amap.location.collection.CollectionConfig::getUploadConfig', {"refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
      kNativeObjectPool.add(com_amap_location_collection_CollectionConfig_UploadConfig()..refId = result..tag = 'amap_location_fluttify');
      return com_amap_location_collection_CollectionConfig_UploadConfig()..refId = result..tag = 'amap_location_fluttify';
    }
  }
  
}