//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:amap_location_fluttify/src/ios/ios.export.g.dart';
import 'package:amap_location_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import
class com_amap_location_common_model_CellStatus_HistoryCell extends java_lang_Object  {
  // generate getters
  Future<int> get_type() async {
    final result = await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod("com.amap.location.common.model.CellStatus.HistoryCell::get_type", {'refId': refId});
  
    return result;
  }
  
  Future<int> get_rssi() async {
    final result = await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod("com.amap.location.common.model.CellStatus.HistoryCell::get_rssi", {'refId': refId});
  
    return result;
  }
  
  Future<int> get_lac() async {
    final result = await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod("com.amap.location.common.model.CellStatus.HistoryCell::get_lac", {'refId': refId});
  
    return result;
  }
  
  Future<int> get_cid() async {
    final result = await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod("com.amap.location.common.model.CellStatus.HistoryCell::get_cid", {'refId': refId});
  
    return result;
  }
  
  Future<int> get_sid() async {
    final result = await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod("com.amap.location.common.model.CellStatus.HistoryCell::get_sid", {'refId': refId});
  
    return result;
  }
  
  Future<int> get_nid() async {
    final result = await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod("com.amap.location.common.model.CellStatus.HistoryCell::get_nid", {'refId': refId});
  
    return result;
  }
  
  Future<int> get_bid() async {
    final result = await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod("com.amap.location.common.model.CellStatus.HistoryCell::get_bid", {'refId': refId});
  
    return result;
  }
  
  Future<int> get_lastUpdateTimeMills() async {
    final result = await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod("com.amap.location.common.model.CellStatus.HistoryCell::get_lastUpdateTimeMills", {'refId': refId});
  
    return result;
  }
  

  // generate setters
  Future<void> set_type(int type) async {
    await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod('com.amap.location.common.model.CellStatus.HistoryCell::set_type', {'refId': refId, "type": type});
  
  
  }
  
  Future<void> set_rssi(int rssi) async {
    await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod('com.amap.location.common.model.CellStatus.HistoryCell::set_rssi', {'refId': refId, "rssi": rssi});
  
  
  }
  
  Future<void> set_lac(int lac) async {
    await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod('com.amap.location.common.model.CellStatus.HistoryCell::set_lac', {'refId': refId, "lac": lac});
  
  
  }
  
  Future<void> set_cid(int cid) async {
    await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod('com.amap.location.common.model.CellStatus.HistoryCell::set_cid', {'refId': refId, "cid": cid});
  
  
  }
  
  Future<void> set_sid(int sid) async {
    await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod('com.amap.location.common.model.CellStatus.HistoryCell::set_sid', {'refId': refId, "sid": sid});
  
  
  }
  
  Future<void> set_nid(int nid) async {
    await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod('com.amap.location.common.model.CellStatus.HistoryCell::set_nid', {'refId': refId, "nid": nid});
  
  
  }
  
  Future<void> set_bid(int bid) async {
    await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod('com.amap.location.common.model.CellStatus.HistoryCell::set_bid', {'refId': refId, "bid": bid});
  
  
  }
  
  Future<void> set_lastUpdateTimeMills(int lastUpdateTimeMills) async {
    await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod('com.amap.location.common.model.CellStatus.HistoryCell::set_lastUpdateTimeMills', {'refId': refId, "lastUpdateTimeMills": lastUpdateTimeMills});
  
  
  }
  

  // generate methods
  Future<com_amap_location_common_model_CellStatus_HistoryCell> clone() async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.amap.location.common.model.CellStatus.HistoryCell@$refId::clone([])');
    }
  
    // invoke native method
    final result = await MethodChannel('me.yohom/amap_location_fluttify').invokeMethod('com.amap.location.common.model.CellStatus.HistoryCell::clone', {"refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
      kNativeObjectPool.add(com_amap_location_common_model_CellStatus_HistoryCell()..refId = result..tag = 'amap_location_fluttify');
      return com_amap_location_common_model_CellStatus_HistoryCell()..refId = result..tag = 'amap_location_fluttify';
    }
  }
  
}